name: 🐛 Bug Report
description: File a bug report to help us improve
title: "[BUG] "
labels: ["bug", "needs-triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 
        Please provide as much detail as possible to help us resolve the issue.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm these before submitting the issue
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I am using the latest version of @xefi/x-react
          required: true

  - type: input
    id: version
    attributes:
      label: Package Version
      description: What version of @xefi/x-react are you using?
      placeholder: "e.g., 1.6.13"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Import component '...'
        2. Use props '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: code-example
    attributes:
      label: Code Example
      description: Please provide a minimal code example that reproduces the issue
      render: tsx
      placeholder: |
        import { Button } from "@xefi/x-react/button"
        
        function Example() {
          return <Button>Click me</Button>
        }

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Your environment details
      placeholder: |
        - OS: [e.g., macOS 13.0, Windows 11, Ubuntu 22.04]
        - Node.js: [e.g., 18.17.0]
        - Package Manager: [e.g., npm 9.6.7, pnpm 8.6.10]
        - Browser: [e.g., Chrome 115, Firefox 116, Safari 16]
        - React: [e.g., 18.2.0]
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Screenshots, error logs, related issues, etc.